[[redirects]]
  from = "/grid/10007"
  to = "/conjuntos"
  status = 301
  force = true

[[redirects]]
  from = "/scripts/*"
  to = "/index"
  status = 301

[[redirects]]
  from = "/grid/*"
  to = "/index"
  status = 301
  
[[redirects]]
  from = "/content/*"
  to = "/index"
  status = 301
  
[[redirects]]
  from = "/marca/100*"
  to = "/index"
  status = 301

[[redirects]]
  from = "/https://www.bluekids.com.br/contate-nos"
  to = "/index"
  status = 301

[[redirects]]
  from = "/https://www.bluekids.com.br/conjunto-tematico-manga-curta-dinossauros-com-gravata-e-suspensorio"
  to = "https://www.bluekids.com.br/roupa-de-festa-camisa-social-dinossauros-com-gravata-e-suspensorio"
  status = 301
  
[[redirects]]
  from = "/https://www.bluekids.com.br/10003"
  to = "/index"
  status = 301
  
[[redirects]]
  from = "/https://www.bluekids.com.br/159-calca"
  to = "/conjunto-com-calca"
  status = 301
