[[redirects]]
  from = "/grid/10007"
  to = "/conjuntos"
  status = 301
  force = true

[[redirects]]
  from = "/scripts/*"
  to = "/index"
  status = 301

[[redirects]]
  from = "/grid/*"
  to = "/index"
  status = 301
  
[[redirects]]
  from = "/content/*"
  to = "/index"
  status = 301
  
[[redirects]]
  from = "/marca/100*"
  to = "/index"
  status = 301

[[redirects]]
  from = "/contate-nos"
  to = "/index"
  status = 301

[[redirects]]
  from = "/conjunto-tematico-manga-curta-dinossauros-com-gravata-e-suspensorio"
  to = "/conjunto-com-bermuda"
  status = 301
  
[[redirects]]
  from = "/10003"
  to = "/index"
  status = 301
  
[[redirects]]
  from = "/159-calca"
  to = "/conjunto-com-calca"
  status = 301
  
[[redirects]]
  from = "/conjunto-com-bermuda/58-conjunto-infantil-camisa-manga-curta-dinossauros-e-bermuda-azul.html"
  to = "/conjunto-com-bermuda"
  status = 301
 
[[redirects]]
  from = "/conjunto-com-bermuda/68-conjunto-camisa-social-menino-manga-curta-circo-com-bermuda.html"
  to = "/conjunto-com-bermuda"
  status = 301
  
[[redirects]]
  from = "/home/101-conjunto-camisa-manga-curta-branca-com-bermuda-e-cinto.html"
  to = "/conjunto-com-bermuda"
  status = 301
  
[[redirects]]
  from = "/home/86-camisa-social-infantil-manga-curta-balao-azul.html"
  to = "/conjunto-com-bermuda"
  status = 301
  
[[redirects]]
  from = "/conjunto-com-bermuda/8-conjunto-camisa-social-infantil-safari-bermuda-verde-e-cinto.html"
  to = "/conjunto-com-bermuda"
  status = 301

[[redirects]]
  from = "/conjunto-com-bermuda/52-conjunto-camisa-social-infantil-safari-com-bermuda.html?search"
  to = "/conjunto-com-bermuda"
  status = 301
  
  [[redirects]]
  from = "/conjunto-com-bermuda/49-conjunto-camisa-social-infantil-manga-curta-baloes-com-bermuda.html"
  to = "/conjunto-com-bermuda"
  status = 301
  
