[[redirects]]
  from = "/grid/10007"
  to = "/conjuntos"
  status = 301
  force = true

[[redirects]]
  from = "/scripts/*"
  to = "/index"
  status = 301

[[redirects]]
  from = "/grid/*"
  to = "/index"
  status = 301
  
[[redirects]]
  from = "/content/*"
  to = "/index"
  status = 301
  
[[redirects]]
  from = "/marca/100*"
  to = "/index"
  status = 301

[[redirects]]
  from = "/contate-nos"
  to = "/index"
  status = 301

[[redirects]]
  from = "/conjunto-tematico-manga-curta-dinossauros-com-gravata-e-suspensorio"
  to = "/roupa-de-festa-camisa-social-dinossauros-com-gravata-e-suspensorio"
  status = 301
  
[[redirects]]
  from = "https://www.bluekids.com.br/10003"
  to = "/index"
  status = 301
  
[[redirects]]
  from = "/159-calca"
  to = "/conjunto-com-calca"
  status = 301
  
  [[redirects]]
  from = "/conjunto-com-bermuda/58-conjunto-infantil-camisa-manga-curta-dinossauros-e-bermuda-azul.html"
  to = "/roupa-de-festa-camisa-social-dinossauros-com-gravata-e-suspensorio"
  status = 301
  
